{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true,
    "ExecuteTime": {
     "end_time": "2023-07-02T12:40:08.387193400Z",
     "start_time": "2023-07-02T12:40:07.692579100Z"
    }
   },
   "outputs": [],
   "source": [
    "#import tensorflow as tf\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import os\n",
    "import pandas as pd\n",
    "from numba import njit\n",
    "from tqdm import tqdm\n",
    "tqdm.pandas()\n",
    "import concurrent.futures"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "outputs": [],
   "source": [
    "\n",
    "MAX_NB_FRAMES = 900\n",
    "DATA_FOLDER = \"/mnt/e/sign-lang-data-2\"\n",
    "\n",
    "#print(all_col)\n"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-07-02T12:40:08.392197200Z",
     "start_time": "2023-07-02T12:40:08.389192500Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "outputs": [],
   "source": [
    "#this notebook is for the purpose of testing a data input pipeline"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-07-02T12:40:08.395193600Z",
     "start_time": "2023-07-02T12:40:08.392197200Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "outputs": [],
   "source": [
    "def load_data(filename):\n",
    "    #filename = filename.numpy().decode(\"utf-8\")\n",
    "\n",
    "    max_nb_frames = MAX_NB_FRAMES\n",
    "    import numpy as np\n",
    "    import pandas as pd\n",
    "    from pathlib import Path\n",
    "    from tqdm import tqdm\n",
    "\n",
    "    seq_label = pd.read_csv(os.path.join(DATA_FOLDER, \"train\", str(filename).replace(\"/\", \"_\") + \".csv\"), sep=\";\")\n",
    "    seq_label = seq_label[[\"sequence_id\", \"phrase\"]]\n",
    "\n",
    "    parquet = pd.read_parquet(os.path.join(DATA_FOLDER, filename), engine='pyarrow')\n",
    "\n",
    "    all_col = list(parquet.columns)\n",
    "\n",
    "    parquet_group = parquet.groupby(\"sequence_id\")\n",
    "\n",
    "    x_face = [col for col in all_col if \"x_face\" in col]\n",
    "    y_face = [col for col in all_col if \"y_face\" in col]\n",
    "    z_face = [col for col in all_col if \"z_face\" in col]\n",
    "\n",
    "    x_left_hand = [col for col in all_col if \"x_left_hand\" in col]\n",
    "    y_left_hand = [col for col in all_col if \"y_left_hand\" in col]\n",
    "    z_left_hand = [col for col in all_col if \"z_left_hand\" in col]\n",
    "\n",
    "    x_right_hand = [col for col in all_col if \"x_right_hand\" in col]\n",
    "    y_right_hand = [col for col in all_col if \"y_right_hand\" in col]\n",
    "    z_right_hand = [col for col in all_col if \"z_right_hand\" in col]\n",
    "\n",
    "    x_pose = [col for col in all_col if \"x_pose\" in col]\n",
    "    y_pose = [col for col in all_col if \"y_pose\" in col]\n",
    "    z_pose = [col for col in all_col if \"z_pose\" in col]\n",
    "\n",
    "    stored_data = np.zeros((len(parquet_group),max_nb_frames, 543, 3))\n",
    "\n",
    "    # crerate a tf tensor with shape (len(parquet_group), 1)\n",
    "\n",
    "\n",
    "    for step, (name, sequence) in enumerate(parquet_group):\n",
    "        for sub_step, (sub_name, timestep) in enumerate(sequence.groupby(\"frame\")):\n",
    "            stored_data[step, sub_step, :468, 0] = timestep[x_face].values\n",
    "            stored_data[step, sub_step, :468, 1] = timestep[y_face].values\n",
    "            stored_data[step, sub_step, :468, 2] = timestep[z_face].values\n",
    "\n",
    "            stored_data[step, sub_step, 468:468 + 21, 0] = timestep[x_left_hand].values\n",
    "            stored_data[step, sub_step, 468:468 + 21, 1] = timestep[y_left_hand].values\n",
    "            stored_data[step, sub_step, 468:468 + 21, 2] = timestep[z_left_hand].values\n",
    "\n",
    "            stored_data[step, sub_step, 468 + 21:468 + 21*2, 0] = timestep[x_right_hand].values\n",
    "            stored_data[step, sub_step, 468 + 21:468 + 21*2, 1] = timestep[y_right_hand].values\n",
    "            stored_data[step, sub_step, 468 + 21:468 + 21*2, 2] = timestep[z_right_hand].values\n",
    "\n",
    "            stored_data[step, sub_step, 468 + 21*2:468 + 21*2 + 33, 0] = timestep[x_pose].values\n",
    "            stored_data[step, sub_step, 468 + 21*2:468 + 21*2 + 33, 1] = timestep[y_pose].values\n",
    "            stored_data[step, sub_step, 468 + 21*2:468 + 21*2 + 33, 2] = timestep[z_pose].values\n",
    "\n",
    "    return stored_data, seq_label.values[:, 1]\n",
    "\n",
    "\n",
    "@njit\n",
    "def fill_data(stored_data, x_face, y_face, z_face, x_left_hand, y_left_hand, z_left_hand, x_right_hand, y_right_hand, z_right_hand, x_pose, y_pose, z_pose, sub_step):\n",
    "\n",
    "    stored_data[sub_step, :468, 0] = x_face\n",
    "    stored_data[sub_step, :468, 1] = y_face\n",
    "    stored_data[sub_step, :468, 2] = z_face\n",
    "\n",
    "    stored_data[sub_step, 468:468 + 21, 0] = x_left_hand\n",
    "    stored_data[sub_step, 468:468 + 21, 1] = y_left_hand\n",
    "    stored_data[sub_step, 468:468 + 21, 2] = z_left_hand\n",
    "\n",
    "    stored_data[sub_step, 468 + 21:468 + 21*2, 0] = x_right_hand\n",
    "    stored_data[sub_step, 468 + 21:468 + 21*2, 1] = y_right_hand\n",
    "    stored_data[sub_step, 468 + 21:468 + 21*2, 2] = z_right_hand\n",
    "\n",
    "    stored_data[sub_step, 468 + 21*2:468 + 21*2 + 33, 0] = x_pose\n",
    "    stored_data[sub_step, 468 + 21*2:468 + 21*2 + 33, 1] = y_pose\n",
    "    stored_data[sub_step, 468 + 21*2:468 + 21*2 + 33, 2] = z_pose\n",
    "\n",
    "def create_npy(filename):\n",
    "    #filename = filename.numpy().decode(\"utf-8\")\n",
    "\n",
    "    max_nb_frames = MAX_NB_FRAMES\n",
    "    import numpy as np\n",
    "    import pandas as pd\n",
    "    from tqdm import tqdm\n",
    "    import time\n",
    "    from pathlib import Path\n",
    "\n",
    "    start = time.time()\n",
    "    parquet = pd.read_parquet(os.path.join(DATA_FOLDER, filename), engine='pyarrow')\n",
    "    end = time.time()\n",
    "    #print(\"time to read parquet file : \", end - start)\n",
    "\n",
    "    all_col = list(parquet.columns)\n",
    "\n",
    "    start = time.time()\n",
    "    parquet_group = parquet.groupby(\"sequence_id\")\n",
    "    end = time.time()\n",
    "    #print(\"time to group parquet file : \", end - start)\n",
    "\n",
    "    x_face = [col for col in all_col if \"x_face\" in col]\n",
    "    y_face = [col for col in all_col if \"y_face\" in col]\n",
    "    z_face = [col for col in all_col if \"z_face\" in col]\n",
    "\n",
    "    x_left_hand = [col for col in all_col if \"x_left_hand\" in col]\n",
    "    y_left_hand = [col for col in all_col if \"y_left_hand\" in col]\n",
    "    z_left_hand = [col for col in all_col if \"z_left_hand\" in col]\n",
    "\n",
    "    x_right_hand = [col for col in all_col if \"x_right_hand\" in col]\n",
    "    y_right_hand = [col for col in all_col if \"y_right_hand\" in col]\n",
    "    z_right_hand = [col for col in all_col if \"z_right_hand\" in col]\n",
    "\n",
    "    x_pose = [col for col in all_col if \"x_pose\" in col]\n",
    "    y_pose = [col for col in all_col if \"y_pose\" in col]\n",
    "    z_pose = [col for col in all_col if \"z_pose\" in col]\n",
    "\n",
    "    #stored_data = np.zeros((len(parquet_group),max_nb_frames, 543, 3))\n",
    "\n",
    "    # crerate a tf tensor with shape (len(parquet_group), 1)\n",
    "\n",
    "    def process_group(name_sequence_pair):\n",
    "        name, sequence = name_sequence_pair\n",
    "        if os.path.exists(os.path.join(DATA_FOLDER, \"npy_train_landmarks\", str(filename).replace(\"/\", \"_\").replace(\".parquet\", \"\") , str(name).replace(\"/\", \"_\") + \".npy\")):\n",
    "            return None, None\n",
    "        stored_data = np.zeros((max_nb_frames, 543, 3))\n",
    "        max_frame = 0\n",
    "        for sub_step, (sub_name, timestep) in enumerate(sequence.groupby(\"frame\")):\n",
    "            fill_data(\n",
    "                stored_data,\n",
    "                timestep[x_face].values, timestep[y_face].values, timestep[z_face].values,\n",
    "                timestep[x_left_hand].values, timestep[y_left_hand].values, timestep[z_left_hand].values,\n",
    "                timestep[x_right_hand].values, timestep[y_right_hand].values, timestep[z_right_hand].values,\n",
    "                timestep[x_pose].values, timestep[y_pose].values, timestep[z_pose].values,\n",
    "                sub_step\n",
    "            )\n",
    "            max_frame = sub_step\n",
    "        Path(os.path.join(DATA_FOLDER, \"npy_train_landmarks\", str(filename).replace(\"/\", \"_\").replace(\".parquet\", \"\"))).mkdir(exist_ok=True)\n",
    "\n",
    "        np.save(\n",
    "            os.path.join(DATA_FOLDER, \"npy_train_landmarks\", str(filename).replace(\"/\", \"_\").replace(\".parquet\", \"\"),\n",
    "                             str(name).replace(\"/\", \"_\") + \".npy\"), stored_data[:max_frame + 1, :, :]\n",
    "                )\n",
    "\n",
    "    with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:\n",
    "        list(executor.map(process_group, parquet_group))\n",
    "\n"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-07-02T12:40:08.428220900Z",
     "start_time": "2023-07-02T12:40:08.401193200Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "outputs": [
    {
     "data": {
      "text/plain": "Index(['path', 'file_id', 'sequence_id', 'participant_id', 'phrase'], dtype='object')"
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "train = pd.read_csv(os.path.join(DATA_FOLDER, \"train.csv\"))\n",
    "train.columns"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-07-02T12:40:08.488343100Z",
     "start_time": "2023-07-02T12:40:08.468829700Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "outputs": [
    {
     "data": {
      "text/plain": "'train_landmarks/5414471.parquet'"
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "train.iloc[0][\"path\"]"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-07-02T12:40:08.495341300Z",
     "start_time": "2023-07-02T12:40:08.491339900Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "outputs": [],
   "source": [
    "#train[\"path\"].drop_duplicates().progress_apply(create_npy)"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-07-02T12:40:08.498341900Z",
     "start_time": "2023-07-02T12:40:08.495341300Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "outputs": [],
   "source": [
    "#@njit()\n",
    "#def optimaze_concatenate(arrays, axis=0):\n",
    "#    return np.concatenate(arrays, axis=axis)\n",
    "\n",
    "\n",
    "def load_npy(npy_path, phrase ):\n",
    "\n",
    "    max_nb_frames = MAX_NB_FRAMES\n",
    "\n",
    "\n",
    "    filename = npy_path.numpy().decode(\"utf-8\")\n",
    "    inputs = np.load(filename)\n",
    "\n",
    "    if inputs.shape[0] > max_nb_frames:\n",
    "        inputs = inputs[:max_nb_frames, :, :]\n",
    "    else:\n",
    "        inputs = np.concatenate([inputs, np.zeros((max_nb_frames - inputs.shape[0], 543, 3))], axis=0)\n",
    "\n",
    "\n",
    "    return inputs, phrase.numpy().decode(\"utf-8\")"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-07-02T12:40:08.549435100Z",
     "start_time": "2023-07-02T12:40:08.501341900Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-07-02 15:22:58.214859: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_12' with dtype resource\n",
      "\t [[{{node Placeholder/_12}}]]\n",
      "2023-07-02 15:22:58.215121: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_5' with dtype int64 and shape [8]\n",
      "\t [[{{node Placeholder/_5}}]]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n",
      "(900, 543, 3)\n",
      "(64, 30000)\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "import tensorflow as tf\n",
    "import keras_nlp\n",
    "import keras\n",
    "\n",
    "with open(\"monBytePairTokenizer.json\", \"r\") as f:\n",
    "    js_file = json.load(f)\n",
    "# %%\n",
    "vocab = js_file[\"model\"][\"vocab\"]\n",
    "merge = js_file[\"model\"][\"merges\"]\n",
    "# %%\n",
    "tokenizer = keras_nlp.tokenizers.BytePairTokenizer(vocab, merge)\n",
    "\n",
    "train[\"npy_path\"] = train[[\"sequence_id\", \"path\"]].apply(\n",
    "    lambda x: os.path.join(DATA_FOLDER, \"npy_train_landmarks\", x[\"path\"].replace(\".parquet\", \"\").replace(\"/\", \"_\") ,str(x[\"sequence_id\"]) + \".npy\"),\n",
    "    axis=1\n",
    ")\n",
    "\n",
    "train_dataset = tf.data.Dataset.from_tensor_slices((train[\"npy_path\"].iloc[:50], train[\"phrase\"].iloc[:50]))\n",
    "\n",
    "# load only the npy\n",
    "train_dataset = train_dataset.map(\n",
    "    lambda npy_path, phrase: tf.py_function(func=load_npy, inp=[npy_path, phrase], Tout=(tf.float32, tf.string)),\n",
    "    num_parallel_calls=tf.data.AUTOTUNE)\n",
    "\n",
    "\n",
    "train_dataset = train_dataset.map(\n",
    "    lambda inputs, label: (inputs, tokenizer.tokenize(label)),\n",
    "    num_parallel_calls=tf.data.AUTOTUNE)\n",
    "\n",
    "# add mask  of 4 to the output\n",
    "def add_mask(inputs, label):\n",
    "    label = label.numpy()\n",
    "    shape = label.shape\n",
    "    new_label = np.full((64), 4)\n",
    "    new_label[:shape[1]] = label[0]\n",
    "    return inputs, new_label\n",
    "\n",
    "train_dataset = train_dataset.map(\n",
    "    lambda inputs, label: tf.py_function(func=add_mask, inp=[inputs, label], Tout=(tf.float32, tf.int32)),\n",
    "    num_parallel_calls=tf.data.AUTOTUNE)\n",
    "\n",
    "# convert to one hot\n",
    "train_dataset = train_dataset.map(\n",
    "    lambda inputs, label: (inputs, tf.one_hot(label, depth=tokenizer.vocabulary_size())),\n",
    "    num_parallel_calls=tf.data.AUTOTUNE)\n",
    "\n",
    "#train_dataset = train_dataset.batch(1)\n",
    "for step, (inputs, label) in enumerate(train_dataset):\n",
    "    print(inputs.shape)\n",
    "    print(label.shape)\n"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-07-02T13:22:59.288730500Z",
     "start_time": "2023-07-02T13:22:56.608503700Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "outputs": [
    {
     "data": {
      "text/plain": "<tf.Tensor: shape=(64, 30000), dtype=float32, numpy=\narray([[0., 1., 0., ..., 0., 0., 0.],\n       [0., 0., 1., ..., 0., 0., 0.],\n       [0., 0., 0., ..., 0., 0., 0.],\n       ...,\n       [1., 0., 0., ..., 0., 0., 0.],\n       [1., 0., 0., ..., 0., 0., 0.],\n       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)>"
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "label = tf.constant([[1, 2, 3]])\n",
    "label = tf.concat([label[0], tf.zeros((64 - label.shape[1],), dtype=tf.int32)], axis=0)\n",
    "\n",
    "tf.one_hot(label, depth=tokenizer.vocabulary_size())"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-07-02T12:41:01.558339Z",
     "start_time": "2023-07-02T12:41:01.502826800Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "outputs": [
    {
     "data": {
      "text/plain": "0        /mnt/e/sign-lang-data-2/npy_train_landmarks/tr...\n1        /mnt/e/sign-lang-data-2/npy_train_landmarks/tr...\n2        /mnt/e/sign-lang-data-2/npy_train_landmarks/tr...\n3        /mnt/e/sign-lang-data-2/npy_train_landmarks/tr...\n4        /mnt/e/sign-lang-data-2/npy_train_landmarks/tr...\n                               ...                        \n67203    /mnt/e/sign-lang-data-2/npy_train_landmarks/tr...\n67204    /mnt/e/sign-lang-data-2/npy_train_landmarks/tr...\n67205    /mnt/e/sign-lang-data-2/npy_train_landmarks/tr...\n67206    /mnt/e/sign-lang-data-2/npy_train_landmarks/tr...\n67207    /mnt/e/sign-lang-data-2/npy_train_landmarks/tr...\nName: npy_path, Length: 67208, dtype: object"
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "train[\"npy_path\"]"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-07-02T08:08:07.021598800Z",
     "start_time": "2023-07-02T08:08:07.017946800Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-07-02 10:29:15.870287: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_6' with dtype resource\n",
      "\t [[{{node Placeholder/_6}}]]\n",
      "2023-07-02 10:29:15.870665: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_9' with dtype string\n",
      "\t [[{{node Placeholder/_9}}]]\n",
      "2023-07-02 10:29:16.640051: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: Shape (63,) must have rank 2\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 265, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 143, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 150, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 809, in wrapped_func\n",
      "    out = func(*structured_inp)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/tmp/ipykernel_7641/2428082220.py\", line 37, in add_mask\n",
      "    return inputs, tf.concat([label, tf.zeros((64 - tf.Tensor.get_shape(label)[0],), dtype=tf.int32)], axis=0)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py\", line 1102, in assert_has_rank\n",
      "    raise ValueError(\"Shape %s must have rank %d\" % (self, rank))\n",
      "\n",
      "ValueError: Shape (63,) must have rank 2\n",
      "\n",
      "\n",
      "2023-07-02 10:29:16.640118: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: ValueError: Shape (63,) must have rank 2\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 265, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 143, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 150, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 809, in wrapped_func\n",
      "    out = func(*structured_inp)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/tmp/ipykernel_7641/2428082220.py\", line 37, in add_mask\n",
      "    return inputs, tf.concat([label, tf.zeros((64 - tf.Tensor.get_shape(label)[0],), dtype=tf.int32)], axis=0)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py\", line 1102, in assert_has_rank\n",
      "    raise ValueError(\"Shape %s must have rank %d\" % (self, rank))\n",
      "\n",
      "ValueError: Shape (63,) must have rank 2\n",
      "\n",
      "\n",
      "\t [[{{node EagerPyFunc}}]]\n",
      "2023-07-02 10:29:16.640582: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: Shape (63,) must have rank 2\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 265, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 143, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 150, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 809, in wrapped_func\n",
      "    out = func(*structured_inp)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/tmp/ipykernel_7641/2428082220.py\", line 37, in add_mask\n",
      "    return inputs, tf.concat([label, tf.zeros((64 - tf.Tensor.get_shape(label)[0],), dtype=tf.int32)], axis=0)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py\", line 1102, in assert_has_rank\n",
      "    raise ValueError(\"Shape %s must have rank %d\" % (self, rank))\n",
      "\n",
      "ValueError: Shape (63,) must have rank 2\n",
      "\n",
      "\n",
      "2023-07-02 10:29:16.640604: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: ValueError: Shape (63,) must have rank 2\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 265, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 143, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 150, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 809, in wrapped_func\n",
      "    out = func(*structured_inp)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/tmp/ipykernel_7641/2428082220.py\", line 37, in add_mask\n",
      "    return inputs, tf.concat([label, tf.zeros((64 - tf.Tensor.get_shape(label)[0],), dtype=tf.int32)], axis=0)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py\", line 1102, in assert_has_rank\n",
      "    raise ValueError(\"Shape %s must have rank %d\" % (self, rank))\n",
      "\n",
      "ValueError: Shape (63,) must have rank 2\n",
      "\n",
      "\n",
      "\t [[{{node EagerPyFunc}}]]\n",
      "2023-07-02 10:29:16.641233: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: Shape (63,) must have rank 2\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 265, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 143, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 150, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 809, in wrapped_func\n",
      "    out = func(*structured_inp)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/tmp/ipykernel_7641/2428082220.py\", line 37, in add_mask\n",
      "    return inputs, tf.concat([label, tf.zeros((64 - tf.Tensor.get_shape(label)[0],), dtype=tf.int32)], axis=0)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py\", line 1102, in assert_has_rank\n",
      "    raise ValueError(\"Shape %s must have rank %d\" % (self, rank))\n",
      "\n",
      "ValueError: Shape (63,) must have rank 2\n",
      "\n",
      "\n",
      "2023-07-02 10:29:16.641253: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: ValueError: Shape (63,) must have rank 2\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 265, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 143, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 150, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 809, in wrapped_func\n",
      "    out = func(*structured_inp)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/tmp/ipykernel_7641/2428082220.py\", line 37, in add_mask\n",
      "    return inputs, tf.concat([label, tf.zeros((64 - tf.Tensor.get_shape(label)[0],), dtype=tf.int32)], axis=0)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py\", line 1102, in assert_has_rank\n",
      "    raise ValueError(\"Shape %s must have rank %d\" % (self, rank))\n",
      "\n",
      "ValueError: Shape (63,) must have rank 2\n",
      "\n",
      "\n",
      "\t [[{{node EagerPyFunc}}]]\n",
      "2023-07-02 10:29:16.641344: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: Shape (63,) must have rank 2\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 265, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 143, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 150, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 809, in wrapped_func\n",
      "    out = func(*structured_inp)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/tmp/ipykernel_7641/2428082220.py\", line 37, in add_mask\n",
      "    return inputs, tf.concat([label, tf.zeros((64 - tf.Tensor.get_shape(label)[0],), dtype=tf.int32)], axis=0)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py\", line 1102, in assert_has_rank\n",
      "    raise ValueError(\"Shape %s must have rank %d\" % (self, rank))\n",
      "\n",
      "ValueError: Shape (63,) must have rank 2\n",
      "\n",
      "\n",
      "2023-07-02 10:29:16.641363: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: ValueError: Shape (63,) must have rank 2\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 265, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 143, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 150, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 809, in wrapped_func\n",
      "    out = func(*structured_inp)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/tmp/ipykernel_7641/2428082220.py\", line 37, in add_mask\n",
      "    return inputs, tf.concat([label, tf.zeros((64 - tf.Tensor.get_shape(label)[0],), dtype=tf.int32)], axis=0)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py\", line 1102, in assert_has_rank\n",
      "    raise ValueError(\"Shape %s must have rank %d\" % (self, rank))\n",
      "\n",
      "ValueError: Shape (63,) must have rank 2\n",
      "\n",
      "\n",
      "\t [[{{node EagerPyFunc}}]]\n",
      "2023-07-02 10:29:16.641465: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: Shape (63,) must have rank 2\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 265, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 143, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 150, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 809, in wrapped_func\n",
      "    out = func(*structured_inp)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/tmp/ipykernel_7641/2428082220.py\", line 37, in add_mask\n",
      "    return inputs, tf.concat([label, tf.zeros((64 - tf.Tensor.get_shape(label)[0],), dtype=tf.int32)], axis=0)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py\", line 1102, in assert_has_rank\n",
      "    raise ValueError(\"Shape %s must have rank %d\" % (self, rank))\n",
      "\n",
      "ValueError: Shape (63,) must have rank 2\n",
      "\n",
      "\n",
      "2023-07-02 10:29:16.641485: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: ValueError: Shape (63,) must have rank 2\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 265, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 143, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 150, in _call\n",
      "    ret = self._func(*args)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 809, in wrapped_func\n",
      "    out = func(*structured_inp)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/tmp/ipykernel_7641/2428082220.py\", line 37, in add_mask\n",
      "    return inputs, tf.concat([label, tf.zeros((64 - tf.Tensor.get_shape(label)[0],), dtype=tf.int32)], axis=0)\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "\n",
      "  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py\", line 1102, in assert_has_rank\n",
      "    raise ValueError(\"Shape %s must have rank %d\" % (self, rank))\n",
      "\n",
      "ValueError: Shape (63,) must have rank 2\n",
      "\n",
      "\n",
      "\t [[{{node EagerPyFunc}}]]\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "{{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ValueError: Shape (63,) must have rank 2\nTraceback (most recent call last):\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 265, in __call__\n    return func(device, token, args)\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 143, in __call__\n    outputs = self._call(device, args)\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 150, in _call\n    ret = self._func(*args)\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 809, in wrapped_func\n    out = func(*structured_inp)\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n    return func(*args, **kwargs)\n\n  File \"/tmp/ipykernel_7641/2428082220.py\", line 37, in add_mask\n    return inputs, tf.concat([label, tf.zeros((64 - tf.Tensor.get_shape(label)[0],), dtype=tf.int32)], axis=0)\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py\", line 1102, in assert_has_rank\n    raise ValueError(\"Shape %s must have rank %d\" % (self, rank))\n\nValueError: Shape (63,) must have rank 2\n\n\n\t [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]",
     "output_type": "error",
     "traceback": [
      "\u001B[0;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[0;31mInvalidArgumentError\u001B[0m                      Traceback (most recent call last)",
      "Cell \u001B[0;32mIn[28], line 1\u001B[0m\n\u001B[0;32m----> 1\u001B[0m \u001B[38;5;28;01mfor\u001B[39;00m step, (inputs, label) \u001B[38;5;129;01min\u001B[39;00m \u001B[38;5;28menumerate\u001B[39m(train_dataset):\n\u001B[1;32m      2\u001B[0m     \u001B[38;5;28mprint\u001B[39m(inputs\u001B[38;5;241m.\u001B[39mshape)\n\u001B[1;32m      3\u001B[0m     \u001B[38;5;28mprint\u001B[39m(label\u001B[38;5;241m.\u001B[39mshape)\n",
      "File \u001B[0;32m~/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py:797\u001B[0m, in \u001B[0;36mOwnedIterator.__next__\u001B[0;34m(self)\u001B[0m\n\u001B[1;32m    795\u001B[0m \u001B[38;5;28;01mdef\u001B[39;00m \u001B[38;5;21m__next__\u001B[39m(\u001B[38;5;28mself\u001B[39m):\n\u001B[1;32m    796\u001B[0m   \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[0;32m--> 797\u001B[0m     \u001B[38;5;28;01mreturn\u001B[39;00m \u001B[38;5;28;43mself\u001B[39;49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43m_next_internal\u001B[49m\u001B[43m(\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    798\u001B[0m   \u001B[38;5;28;01mexcept\u001B[39;00m errors\u001B[38;5;241m.\u001B[39mOutOfRangeError:\n\u001B[1;32m    799\u001B[0m     \u001B[38;5;28;01mraise\u001B[39;00m \u001B[38;5;167;01mStopIteration\u001B[39;00m\n",
      "File \u001B[0;32m~/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py:780\u001B[0m, in \u001B[0;36mOwnedIterator._next_internal\u001B[0;34m(self)\u001B[0m\n\u001B[1;32m    777\u001B[0m \u001B[38;5;66;03m# TODO(b/77291417): This runs in sync mode as iterators use an error status\u001B[39;00m\n\u001B[1;32m    778\u001B[0m \u001B[38;5;66;03m# to communicate that there is no more data to iterate over.\u001B[39;00m\n\u001B[1;32m    779\u001B[0m \u001B[38;5;28;01mwith\u001B[39;00m context\u001B[38;5;241m.\u001B[39mexecution_mode(context\u001B[38;5;241m.\u001B[39mSYNC):\n\u001B[0;32m--> 780\u001B[0m   ret \u001B[38;5;241m=\u001B[39m \u001B[43mgen_dataset_ops\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43miterator_get_next\u001B[49m\u001B[43m(\u001B[49m\n\u001B[1;32m    781\u001B[0m \u001B[43m      \u001B[49m\u001B[38;5;28;43mself\u001B[39;49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43m_iterator_resource\u001B[49m\u001B[43m,\u001B[49m\n\u001B[1;32m    782\u001B[0m \u001B[43m      \u001B[49m\u001B[43moutput_types\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[38;5;28;43mself\u001B[39;49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43m_flat_output_types\u001B[49m\u001B[43m,\u001B[49m\n\u001B[1;32m    783\u001B[0m \u001B[43m      \u001B[49m\u001B[43moutput_shapes\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[38;5;28;43mself\u001B[39;49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43m_flat_output_shapes\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    785\u001B[0m   \u001B[38;5;28;01mtry\u001B[39;00m:\n\u001B[1;32m    786\u001B[0m     \u001B[38;5;66;03m# Fast path for the case `self._structure` is not a nested structure.\u001B[39;00m\n\u001B[1;32m    787\u001B[0m     \u001B[38;5;28;01mreturn\u001B[39;00m \u001B[38;5;28mself\u001B[39m\u001B[38;5;241m.\u001B[39m_element_spec\u001B[38;5;241m.\u001B[39m_from_compatible_tensor_list(ret)  \u001B[38;5;66;03m# pylint: disable=protected-access\u001B[39;00m\n",
      "File \u001B[0;32m~/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/gen_dataset_ops.py:3016\u001B[0m, in \u001B[0;36miterator_get_next\u001B[0;34m(iterator, output_types, output_shapes, name)\u001B[0m\n\u001B[1;32m   3014\u001B[0m   \u001B[38;5;28;01mreturn\u001B[39;00m _result\n\u001B[1;32m   3015\u001B[0m \u001B[38;5;28;01mexcept\u001B[39;00m _core\u001B[38;5;241m.\u001B[39m_NotOkStatusException \u001B[38;5;28;01mas\u001B[39;00m e:\n\u001B[0;32m-> 3016\u001B[0m   \u001B[43m_ops\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mraise_from_not_ok_status\u001B[49m\u001B[43m(\u001B[49m\u001B[43me\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mname\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m   3017\u001B[0m \u001B[38;5;28;01mexcept\u001B[39;00m _core\u001B[38;5;241m.\u001B[39m_FallbackException:\n\u001B[1;32m   3018\u001B[0m   \u001B[38;5;28;01mpass\u001B[39;00m\n",
      "File \u001B[0;32m~/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/ops.py:7262\u001B[0m, in \u001B[0;36mraise_from_not_ok_status\u001B[0;34m(e, name)\u001B[0m\n\u001B[1;32m   7260\u001B[0m \u001B[38;5;28;01mdef\u001B[39;00m \u001B[38;5;21mraise_from_not_ok_status\u001B[39m(e, name):\n\u001B[1;32m   7261\u001B[0m   e\u001B[38;5;241m.\u001B[39mmessage \u001B[38;5;241m+\u001B[39m\u001B[38;5;241m=\u001B[39m (\u001B[38;5;124m\"\u001B[39m\u001B[38;5;124m name: \u001B[39m\u001B[38;5;124m\"\u001B[39m \u001B[38;5;241m+\u001B[39m name \u001B[38;5;28;01mif\u001B[39;00m name \u001B[38;5;129;01mis\u001B[39;00m \u001B[38;5;129;01mnot\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m \u001B[38;5;28;01melse\u001B[39;00m \u001B[38;5;124m\"\u001B[39m\u001B[38;5;124m\"\u001B[39m)\n\u001B[0;32m-> 7262\u001B[0m   \u001B[38;5;28;01mraise\u001B[39;00m core\u001B[38;5;241m.\u001B[39m_status_to_exception(e) \u001B[38;5;28;01mfrom\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m\n",
      "\u001B[0;31mInvalidArgumentError\u001B[0m: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ValueError: Shape (63,) must have rank 2\nTraceback (most recent call last):\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 265, in __call__\n    return func(device, token, args)\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 143, in __call__\n    outputs = self._call(device, args)\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 150, in _call\n    ret = self._func(*args)\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py\", line 809, in wrapped_func\n    out = func(*structured_inp)\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 642, in wrapper\n    return func(*args, **kwargs)\n\n  File \"/tmp/ipykernel_7641/2428082220.py\", line 37, in add_mask\n    return inputs, tf.concat([label, tf.zeros((64 - tf.Tensor.get_shape(label)[0],), dtype=tf.int32)], axis=0)\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n\n  File \"/home/dev/miniconda3/envs/sign-lang/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py\", line 1102, in assert_has_rank\n    raise ValueError(\"Shape %s must have rank %d\" % (self, rank))\n\nValueError: Shape (63,) must have rank 2\n\n\n\t [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]"
     ]
    }
   ],
   "source": [],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-07-02T08:29:16.681037700Z",
     "start_time": "2023-07-02T08:29:15.848069300Z"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
